name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --prefix \job-artefacts-outputs-demo\
      - name: Lint code
        run: npm run lint --prefix \job-artefacts-outputs-demo\
      - name: Test code
        run: npm run test --prefix \job-artefacts-outputs-demo\
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --prefix \job-artefacts-outputs-demo\
      - name: Build website
        run: npm run build --prefix \job-artefacts-outputs-demo\
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
