# Name of the workflow
name: First Workflow
# Events that trigger workflows: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
# Define when this workflow should be executed, and the event(s) that should trigger this workflow to run
on: workflow_dispatch
# Define the works that should be done
jobs:
  # Name of the job
  first-job:
    # Define the runner/environment on which the steps will execute
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-latest
    # Define the steps that should be executed
    steps:
      # Key-value pairs that describe the steps
      - name: Print greeting
        # Define a command that will be used in the command line
        run: echo "Hello World!"
      - name: Print goodbye
        # Define a command that will be used in the command line
        run: echo "Done - goodbye!"
