# Run src/components/MainContent.test.jsx tests whenever you push or commit to Github
name: Deploy React Demo Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download the code from the repository
        # Action Checkout V4
        uses: actions/checkout@v4
      # Optional since Nodejs is already installed in ubuntu
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci --prefix \react-demo\ # Targets the project folder
      - name: Run Tests
        run: npm test --prefix \react-demo\ # Targets the project folder
  deploy:
    needs: test # Points to the identity of another job that must finish before this job (runs sequentially)
    runs-on: ubuntu-latest
    steps:
      - name: Download the code from the repository
        # Action Checkout V4
        uses: actions/checkout@v4
      # Optional since Nodejs is already installed in ubuntu
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci --prefix \react-demo\ # Targets the project folder
      - name: Build Project
        run: npm run build --prefix \react-demo\ # Targets the project folder
      - name: Deploying to Hosting Server
        run: echo "Deploying..."
      - name: Deploy success
        run: echo "Deployed successfully!"
